import React from "react";

export const steps = [
  "The Basics",
  "Player Info",
  "Location Details",
  "Session Details",
  "Game Style",
  "Other",
];

export const options = [
  {
    system: "Dungeons & Dragons",
    versions: [
      "Original Edition",
      "AD&D 1st Edition",
      "AD&D 2nd Edition",
      "3rd Edition",
      "Version 3.5",
      "4th Edition",
      "5th Edition",
    ],
  },
  {
    system: "Pathfinder",
    versions: ["First Edition", "Second Edition"],
  },
  {
    system: "Vampire: The Masquerade",
    versions: [
      "Original Edition",
      "Second Edition",
      "Revised Edition",
      "20th Anniversary Edition",
      "5th Edition",
    ],
  },
  {
    system: "Starfinder",
    versions: ["First Edition"],
  },
  {
    system: "Call of Cthulhu",
    versions: [
      "1st edition",
      "2nd edition",
      "3rd edition",
      "4th edition",
      "5th edition",
      "Edition 5.5",
      "20th Anniversary Edition",
      "6th edition",
      "7th edition",
    ],
  },
  {
    system: "Shadowrun",
    versions: [
      "1st edition",
      "2nd edition",
      "3rd edition",
      "4th edition",
      "5th edition",
      "6th edition",
    ],
  },
  {
    system: "FATE",
    versions: [
      "Original Edition",
      "2nd Edition",
      "3rd Edition",
      "FATE Core",
      "FATE Accelerated Edition",
    ],
  },
];

export const languages = [
  "Abkhaz",
  "Afar",
  "Afrikaans",
  "Akan",
  "Albanian",
  "Amharic",
  "Arabic",
  "Aragonese",
  "Armenian",
  "Assamese",
  "Avaric",
  "Avestan",
  "Aymara",
  "Azerbaijani",
  "Bambara",
  "Bashkir",
  "Basque",
  "Belarusian",
  "Bengali",
  "Bihari",
  "Bislama",
  "Bosnian",
  "Breton",
  "Bulgarian",
  "Burmese",
  "Catalan",
  "Chamorro",
  "Chechen",
  "Chichewa",
  "Chinese",
  "Chuvash",
  "Cornish",
  "Corsican",
  "Cree",
  "Croatian",
  "Czech",
  "Danish",
  "Divehi",
  "Dutch",
  "English",
  "Esperanto",
  "Estonian",
  "Ewe",
  "Faroese",
  "Fijian",
  "Finnish",
  "French",
  "Fula",
  "Galician",
  "Georgian",
  "German",
  "Greek",
  "Guaraní",
  "Gujarati",
  "Haitia",
  "Hausa",
  "Hebrew",
  "Herero",
  "Hindi",
  "Hiri Motu",
  "Hungarian",
  "Interlingua",
  "Indonesian",
  "Interlingue",
  "Irish",
  "Igbo",
  "Inupiaq",
  "Ido",
  "Icelandic",
  "Italian",
  "Inuktitut",
  "Japanese",
  "Javanese",
  "Kalaallisut",
  "Kannada",
  "Kanuri",
  "Kashmiri",
  "Kazakh",
  "Khmer",
  "Kikuyu",
  "Kinyarwanda",
  "Kirghiz",
  "Komi",
  "Kongo",
  "Korean",
  "Kurdish",
  "Kwanyama",
  "Latin",
  "Luxembourgish",
  "Luganda",
  "Limburgish",
  "Lingala",
  "Lao",
  "Lithuanian",
  "Luba-Katanga",
  "Latvian",
  "Manx",
  "Macedonian",
  "Malagasy",
  "Malay",
  "Malayalam",
  "Maltese",
  "Māori",
  "Marathi",
  "Marshallese",
  "Mongolian",
  "Nauru",
  "Navajo",
  "North Ndebele",
  "Nepali",
  "Ndonga",
  "Norwegian",
  "Nuosu",
  "South Ndebele",
  "Occitan",
  "Ojibwe",
  "Oromo",
  "Oriya",
  "Ossetian",
  "Panjabi",
  "Pāli",
  "Persian",
  "Polish",
  "Pashto",
  "Portuguese",
  "Quechua",
  "Romansh",
  "Kirundi",
  "Romanian",
  "Russian",
  "Sanskrit",
  "Sardinian",
  "Sindhi",
  "Northern Sami",
  "Samoan",
  "Sango",
  "Serbian",
  "Scottish Gaelic",
  "Shona",
  "Sinhala",
  "Slovak",
  "Slovene",
  "Somali",
  "Southern Sotho",
  "Spanish",
  "Sundanese",
  "Swahili",
  "Swati",
  "Swedish",
  "Tamil",
  "Telugu",
  "Tajik",
  "Thai",
  "Tigrinya",
  "Tibetan",
  "Turkmen",
  "Tagalog",
  "Tswana",
  "Tonga",
  "Turkish",
  "Tsonga",
  "Tatar",
  "Twi",
  "Tahitian",
  "Uighur",
  "Ukrainian",
  "Urdu",
  "Uzbek",
  "Venda",
  "Vietnamese",
  "Volapük",
  "Walloon",
  "Welsh",
  "Wolof",
  "Western Frisian",
  "Xhosa",
  "Yiddish",
  "Yoruba",
  "Zhuang",
];

export const tagList = [
  "Absurd",
  "Adults Only",
  "Casual",
  "Character Driven",
  "Combat-heavy",
  "Comedy",
  "Dark",
  "Dragonlance",
  "Dungeon Crawler",
  "Eberron",
  "Epic Fantasy",
  "Forgotten Realms",
  "Fun Prioritized",
  "Gothic",
  "Grim",
  "Hardcore Play",
  "Heavy Prep",
  "High Magic",
  "High Tier",
  "Homebrew",
  "Horror",
  "Improvisation",
  "Kid-friendly",
  "Low Magic",
  "Low Tier",
  "Maraton Sessions",
  "Mediaval",
  "Mid Tier",
  "Multiple GM",
  "Murderhobo",
  "New GM",
  "No Prep",
  "Old School",
  "Open-world",
  "Prewritten",
  "Railroad",
  "Realistic",
  "RP-heavy",
  "Rule of Fun",
  "Rules-heavy",
  "Sandbox",
  "Serious",
  "Solo",
  "Strategic",
  "Urban",
  "Vampire",
  "Werewolf",
  "Worldbuilding",
];

export const marks = [
  {
    value: 0,
    label: "Beginner",
  },
  {
    value: 25,
    label: "Novice",
  },
  {
    value: 50,
    label: "Moderate",
  },
  {
    value: 75,
    label: "Seasoned",
  },
  {
    value: 100,
    label: "Pro",
  },
];

export const defaultValues = {
  gameSystem: "",
  gameVersion: "",
  adventureName: "",
  adventureLength: "",
  language: "",
  totalPlayerCount: null,
  currentPlayerCount: null,
  playerExpLevel: "",
  medium: "",
  platform: "",
  communicationMethod: "",
  location: "",
  hosting: "",
  sessionFrequency: null,
  sessionLength: null,
  gmTimeZone: null,
  sessionDay: "",
  sessionHour: null,
  gameStyle: "",
  gmStyle: "",
  adventureStyle: "",
  gmExperinceLevel: "",
  storyGenre: "",
  campaignPrimer: "",
  storyStyle: "",
  tags: [],
};
